# Generated by Django 3.1 on 2020-08-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200830_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commnet_author',
            new_name='comment_author',
        ),
    ]
